name: "Check spelling"
on: # rebuild any PRs
  pull_request:

permissions:
  contents: read

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: streetsidesoftware/cspell-action@e464ae97d348eb3beb0c5a6296dc4388ad4484d9 # v6.11.1
        with:
          # Specify the files to check
          files: "**/*.{md,html,js,ts,css}"
          config: ".github/workflows/cspell.json"
